### ISSUE TITLE
'MemoryError' when concatenate 'triple_pos' and  'triple_neg' array

### ISSUE THREAD

**Issue by bbjy** [bio-ontology-research-group/DeepViral#1]
Hi @ChaseWLW , thank you for your work. 
When I reproduce your work, I met the 'MemoryError'  when concatenating 'triple_pos' and  'triple_neg' array while training the model.  The error information is as follows:
`numpy.core._exceptions.MemoryError: Unable to allocate 10.9GiB for an array with shape (14661920, 4) and data type <U50 `

Would you please tell me that the memory of this work needed if you process the training data as the released code.
https://github.com/bio-ontology-research-group/DeepViral/blob/1d4ec7a4f488b0930ca1d27877a49c0e115acb20/utils.py#L142

Or some other options to process the data?

**Comment by ChaseWLW** [comment]
Hi @bbjy, I was using Tesla V100 GPUs for training with 32 GB memory. You might consider reducing the training batch sizes to avoid this error.

**Comment by bbjy** [comment]
> Hi @bbjy, I was using Tesla V100 GPUs for training with 32 GB memory. You might consider reducing the training batch sizes to avoid this error.

Thank you for your reply. But, it seems not the matter of batch size, since this 'concatenate' operation is to construct total triples of training dataset before loading data by batch.

**Comment by ChaseWLW** [comment]
Hey @bbjy, sorry you are right. I can't remember exactly how much memory the code needs to run, but it should be in the range of 40-70 GB ram. This is likely too big for a personal computer, you might consider subsampling the triples before concatenating them.

**Comment by bbjy** [comment]
> Hey @bbjy, sorry you are right. I can't remember exactly how much memory the code needs to run, but it should be in the range of 40-70 GB ram. This is likely too big for a personal computer, you might consider subsampling the triples before concatenating them.

Thank you! I try to sample negative triples as the size 10*len(triple_pos), it could avoid the memory error. But the reproduced results  (with the default parameters in released code) are lower than the paper,  shown as follows. 

`vp_aucss: mean: 0.728715912965914, mean-interval: 0.7116820705886605, mean+interval: 0.7457497553431675

taxon_aucss: mean: 0.7438694978880276, mean-interval: 0.7313384141949065, mean+interval: 0.7564005815811486

family_aucss: mean: 0.7752160669651238, mean-interval:  0.7685264457857413, mean+interval: 0.7819056881445063

mean_mean_ranks: 3788.488678174893`

Do you think the lower results are due to the reduction of training negative triples? Or is there any difference between the parameters  the paper used and the released code showed?

Thanks again for your prompt reply!

**Comment by ChaseWLW** [comment]
Sorry for the late reply! 

The neural network parameters were always fixed for the experiments in the paper. The drop in performance could be explained by the smaller set of negatives, maybe you could try changing it and see if it makes a difference. Did you run the "joint" model for the above results?
